/* PUNTO NUMERO -------1------------Creacion  Tabla Familia*/
-- SE CREA LA TABLA FAMILIA Y SE INDICA LA CLAVE PRIMARIA COD FAMILIA:
CREATE TABLE FAMILIA 
( CODFAMILIA int(3) not null,
DENOFAMILIA VARCHAR(50) NOT NULL ,
 CONSTRAINT FAMILIA_PK PRIMARY KEY  (CODFAMILIA)
  );-- SE CREA LA TABLA FAMILIA Y SE INDICA LA CLAVE PRIMARIA COD FAMILIA.

-- SE APLICA LA RESTRICCION DATO UNICO EN DENOFAMILIA:
ALTER TABLE FAMILIA
ADD CONSTRAINT FAMILIA_UK UNIQUE 
(DENOFAMILIA); -- SE APLICA LA RESTRICCION DATO UNICO EN DENOFAMILIA.

/* PUNTO NUMERO -------2------------Creacion Tabla PRODUCTO*/
-- SE CREA LA TABLA PRODUCTO Y SE INDICA LA CLAVE PRIMARIA CODPRODUCTO:
CREATE TABLE PRODUCTO 
(
CODPRODUCTO         INT(5)       NOT NULL 
, DENOPRODUCTO      VARCHAR(20)    NOT NULL 
, DESCRIPCION       VARCHAR(100)   
, PRECIOBASE        DECIMAL(8,2)    
, PORCREPOSICION    INT(3)    
, UNIDADESMINIMAS   int (4)      NOT NULL
, CODFAMILIA        INT(3)       NOT NULL
, CONSTRAINT PRODUCTO_PK PRIMARY KEY 
    (CODPRODUCTO)
  );
  
-- RESTRICCIONES PARA VALORES MAYORES A 0 Y CLAVE FORANEA CODFAMILIA:
ALTER TABLE PRODUCTO ADD CONSTRAINT PRECIOBASE_CK 
CHECK (PRECIOBASE >0); 
ALTER TABLE PRODUCTO ADD CONSTRAINT PORCREPOSICION_CK 
CHECK (PORCREPOSICION >0); 
ALTER TABLE PRODUCTO ADD CONSTRAINT UNIDADESMINIMAS_CK 
CHECK (UNIDADESMINIMAS >0); 
ALTER TABLE PRODUCTO ADD CONSTRAINT CODFAMILIA_FK 
FOREIGN KEY (Codfamilia) 
REFERENCES FAMILIA (CODFAMILIA); 




/* PUNTO NUMERO -------3------------Creacion Tabla TIENDA*/
-- SE CREA LA TABLA TIENDA Y SE INDICA LA CLAVE PRIMARIA CODTIENDA:
CREATE TABLE TIENDA 
(
  CODTIENDA         int(3)       NOT NULL 
, DENOTIENDA        VARCHAR(20)    NOT NULL 
, TELEFONO          VARCHAR(11)   
, CODIGOPOSTAL      VARCHAR(5)     NOT NULL    
, PROVINCIA         VARCHAR(5)     NOT NULL
, CONSTRAINT TIENDA_PK PRIMARY KEY 
    (CODTIENDA)
  );
  
  /* PUNTO NUMERO -------4------------Creacion Tabla STOCK*/
-- SE CREA LA TABLA STOCK Y SE INDICA CLAVE PRINCIPAL CODTIENDA Y CODPRODUCTO:
CREATE TABLE STOCK 
(
  CODTIENDA         int(3)       NOT NULL 
, CODPRODUCTO       int(5)       NOT NULL 
, UNIDADES          int(6)       NOT NULL   
, CONSTRAINT STOCK_PK PRIMARY KEY 
    (CODTIENDA, CODPRODUCTO)
  );
  -- RESTRICCIONES PARA CLAVES FORANEAS CODTIENDA Y CODPRODUCTO:

ALTER TABLE STOCK ADD CONSTRAINT FK_CODTIENDA 
FOREIGN KEY (CODTIENDA)
REFERENCES TIENDA (CODTIENDA);

ALTER TABLE STOCK ADD CONSTRAINT FK_CODPRODUCTO 
FOREIGN KEY (CODPRODUCTO)
REFERENCES PRODUCTO (CODPRODUCTO);

-- RESTRICCIONES PARA CONTENIDO MAYOR QUE 0 EN UNIDADES:
ALTER TABLE STOCK ADD CONSTRAINT CK_UNIDADES 
CHECK (UNIDADES >0); 


  

