                                                                                                                
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE LOGMNR_SESSION_EVOLVE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_GLOBAL$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_PDB_INFO$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_DID$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_UID$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNRGGC_GTLO CASCADE CONSTRAINTS;
DROP TABLE LOGMNRGGC_GTCS CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_DBNAME_UID_MAP CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_LOG$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_PROCESSED_LOG$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_SPILL$ CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE LOGMNR_AGE_SPILL$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_RESTART_CKPT_TXINFO$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_ERROR$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_RESTART_CKPT$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_FILTER$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_SESSION_ACTIONS$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_PARAMETER$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_SESSION$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_PROFILE_TABLE_STATS$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_PROFILE_PLSQL_STATS$ CASCADE CONSTRAINTS;
DROP TABLE REDO_DB CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE REDO_LOG CASCADE CONSTRAINTS;
DROP TABLE ROLLING$CONNECTIONS CASCADE CONSTRAINTS;
DROP TABLE ROLLING$DATABASES CASCADE CONSTRAINTS;
DROP TABLE ROLLING$DIRECTIVES CASCADE CONSTRAINTS;
DROP TABLE ROLLING$EVENTS CASCADE CONSTRAINTS;
DROP TABLE ROLLING$PARAMETERS CASCADE CONSTRAINTS;
DROP TABLE ROLLING$PLAN CASCADE CONSTRAINTS;
DROP TABLE ROLLING$STATISTICS CASCADE CONSTRAINTS;
DROP TABLE ROLLING$STATUS CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_WORKLOAD CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_BASETABLE CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE MVIEW$_ADV_SQLDEPEND CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_PRETTY CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_TEMP CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_FILTER CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_LOG CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_FILTERINSTANCE CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_LEVEL CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_ROLLUP CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_AJG CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_FJG CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_GC CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE MVIEW$_ADV_CLIQUE CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_ELIGIBLE CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_OUTPUT CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_EXCEPTIONS CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_PARAMETERS CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_INFO CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_JOURNAL CASCADE CONSTRAINTS;
DROP TABLE MVIEW$_ADV_PLAN CASCADE CONSTRAINTS;
DROP TABLE AQ$_QUEUE_TABLES CASCADE CONSTRAINTS;
DROP TABLE AQ$_KEY_SHARD_MAP CASCADE CONSTRAINTS;
DROP TABLE AQ$_QUEUES CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE AQ$_SCHEDULES CASCADE CONSTRAINTS;
DROP TABLE AQ$_INTERNET_AGENTS CASCADE CONSTRAINTS;
DROP TABLE AQ$_INTERNET_AGENT_PRIVS CASCADE CONSTRAINTS;
DROP TABLE SCHEDULER_PROGRAM_ARGS_TBL CASCADE CONSTRAINTS;
DROP TABLE SCHEDULER_JOB_ARGS_TBL CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$APPLY_MILESTONE CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$SCN CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$FLASHBACK_SCN CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$PLSQL CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$SKIP_TRANSACTION CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$SKIP CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE LOGSTDBY$SKIP_SUPPORT CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$HISTORY CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$EDS_TABLES CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$PARAMETERS CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$EVENTS CASCADE CONSTRAINTS;
DROP TABLE SQLPLUS_PRODUCT_PROFILE CASCADE CONSTRAINTS;
DROP TABLE HELP CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_GT_TAB_INCLUDE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_GT_USER_INCLUDE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_GT_XID_INCLUDE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNRT_MDDL$ CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE OL$ CASCADE CONSTRAINTS;
DROP TABLE OL$HINTS CASCADE CONSTRAINTS;
DROP TABLE OL$NODES CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_DICTSTATE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_GTLO CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_GTCS CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_SEQ_GG CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_CON_GG CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_CONCOL_GG CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_IND_GG CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_INDCOL_GG CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE LOGMNRC_SHARD_TS CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_TSPART CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_TS CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_GSII CASCADE CONSTRAINTS;
DROP TABLE LOGMNRC_GSBA CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_SEED$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_DICTIONARY$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_OBJ$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_TAB$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_COL$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_ATTRCOL$ CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE LOGMNR_TS$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_IND$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_USER$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_TABPART$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_TABSUBPART$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_TABCOMPART$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_TYPE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_COLTYPE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_ATTRIBUTE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_LOB$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_CON$ CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE LOGMNR_CONTAINER$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_CDEF$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_CCOL$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_ICOL$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_LOBFRAG$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_INDPART$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_INDSUBPART$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_INDCOMPART$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_LOGMNR_BUILDLOG CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_NTAB$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_OPQTYPE$ CASCADE CONSTRAINTS;

'DROPTABLE'||TABLE_NAME||'CASCADECONSTRAINTS;'                                                                                                                  
----------------------------------------------------------------------------------------------------------------------------------------------------------------
DROP TABLE LOGMNR_SUBCOLTYPE$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_KOPM$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_PROPS$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_ENC$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_REFCON$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_IDNSEQ$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_PARTOBJ$ CASCADE CONSTRAINTS;
DROP TABLE LOGMNRP_CTAS_PART_MAP CASCADE CONSTRAINTS;
DROP TABLE LOGMNR_SHARD_TS CASCADE CONSTRAINTS;
DROP TABLE LOGSTDBY$APPLY_PROGRESS CASCADE CONSTRAINTS;

